sitepr/sitepr/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
 path('votacao/', include('votacao.urls')),
 path('admin/', admin.site.urls),
 path('projeto/', include('projeto.urls')),
]

sitepr/votacao/urls.py
from django.urls import include, path
from . import views
# (. significa que importa views da mesma directoria)

app_name = 'votacao'
urlpatterns = [
# ex: votacao/
 path("", views.index, name='index'),
 # ex: votacao/1
 path('<int:questao_id>', views.detalhe, name='detalhe'),
 # ex: votacao/3/resultados
 path('<int:questao_id>/resultados', views.resultados, name='resultados'),
 # ex: votacao/5/voto
 path('<int:questao_id>/voto', views.voto, name='voto'),
# ex: votacao/novaquestao
 path("gravarquestao", views.gravarquestao, name='gravarquestao'),

 path("novaquestao", views.novaquestao, name='novaquestao'),

 path("<int:questao_id>/novaopcao", views.novaopcao, name='novaopcao'),

 path("<int:questao_id>/gravaropcao", views.gravaropcao, name='gravaropcao'),

 path("listarquestao", views.listarquestao, name='listarquestao'),

 path("apagarquestao", views.apagarquestao, name='apagarquestao'),

 path("<int:questao_id>/listaropcao", views.listaropcao, name='listaropcao'),

 path("<int:questao_id>/apagaropcao", views.apagaropcao, name='apagaropcao'),
]

sitepr/votacao/models.py
from django.db import models
from django.utils import timezone
import datetime

class Questao(models.Model):
    questao_texto = models.CharField(max_length=200)
    pub_data = models.DateTimeField('data de publicacao')
    def __str__(self):
        return self.questao_texto
    def foi_publicado_recentemente(self):
        return self.pub_data >= timezone.now() - datetime.timedelta(days=1)


class Opcao(models.Model):
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    opcao_texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

sitepr/votacao/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.utils import timezone

from .models import Questao, Opcao

def index(request):
    latest_question_list = Questao.objects.order_by('-pub_data')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'votacao/index.html', context)

def detalhe(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/detalhe.html', {'questao': questao})


def voto(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        opcao_seleccionada = questao.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
    # Apresenta de novo o form para votar
        return render(request, 'votacao/detalhe.html', {'questao': questao,'error_message': "Não escolheu uma opção",})
    else:
        opcao_seleccionada.votos += 1
        opcao_seleccionada.save()
    # Retorne sempre HttpResponseRedirect depois de
    # tratar os dados POST de um form
    # pois isso impede os dados de serem tratados
    # repetidamente se o utilizador
    # voltar para a página web anterior.
        return HttpResponseRedirect(reverse('votacao:resultados', args=(questao.id,)))

def resultados(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request,'votacao/resultados.html',{'questao': questao})

def novaquestao(request):
    return render(request, 'votacao/novaquestao.html')

def gravarquestao(request):
    if request.method == 'POST':
        if request.POST.get('fnovaquestao'):
            questao = Questao()
            questao.questao_texto = request.POST['fnovaquestao']
            questao.pub_data= timezone.now()
            questao.save()
    #context = {'fnovaquestao':fnovaquestao}
            return HttpResponseRedirect(reverse('votacao:index'))

def novaopcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/nova_opcao.html',{'questao': questao})

def gravaropcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    opcao = Opcao()
    opcao.opcao_texto = request.POST['fnovaopcao']
    opcao.votos = 0
    opcao.questao = questao
    opcao.save()
    return HttpResponseRedirect(reverse('votacao:detalhe', args=(questao.id,)))


def listarquestao(request):
    question_list = Questao.objects.all()
    context = {'question_list': question_list}
    return render(request, 'votacao/listar_questao.html', context)

def apagarquestao(request):
    try:
        questao = Questao.objects.get(pk=request.POST['questao'])
    except (KeyError, Questao.DoesNotExist):
        # Apresenta de novo o form para votar
        return render(request, 'votacao/listar_questao.html',  {'error_message': "Não escolheu uma opção"})
    else:
        questao.delete()
    return HttpResponseRedirect(reverse('votacao:index'))

def listaropcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/listar_opcao.html', {'questao': questao})

def apagaropcao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        opcao_seleccionada = questao.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        # Apresenta de novo o form para votar
        return render(request, 'votacao/listar_opcao.html', {'questao': questao, 'error_message': "Não escolheu uma opção", })
    else:
        opcao_seleccionada.delete()

    return HttpResponseRedirect(reverse('votacao:detalhe', args=(questao.id,)))

sitepr/votacao/templates/votacao/detalhe.html
<h2>{{ questao.questao_texto }}</h2>
{% if error_message %}
 <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'votacao:voto' questao.id %}" method="post">
 {% csrf_token %}
 {% for opcao in questao.opcao_set.all %}
 <input type="radio" name="opcao" id="opcao{{ forloop.counter }}" value="{{ opcao.id }}" />
 <label for="opcao{{ forloop.counter }}">
 {{ opcao.opcao_texto }}
 </label>
 <br />
 {% endfor %}
 <input type="submit" value="Voto" />
</form>
<p>
 <a href="{%url 'votacao:novaopcao' questao.id %}"> Criar nova opção</a>
</p>

<p>
 <a href="{%url 'votacao:listaropcao' questao.id %}"> Apagar opção</a>
</p>

sitepr/votacao/templates/votacao/index.html
{% load static %}

<link rel="stylesheet" type="text/css"
 href="{% static 'votacao/style.css' %}" />

<h3>
{% if latest_question_list %}
<ul>
 {% for questao in latest_question_list %}
 <li>
  <a href="{% url 'votacao:detalhe' questao.id %}" class="button3"> {{ questao.questao_texto }} </a>
 </li>
 {% endfor %}
</ul>
{% else %}
<p>Nao ha questoes disponiveis.</p>
{% endif %}
 </h3>
<p>
 <a href="{%url 'votacao:novaquestao' %}"> Nova questão</a>
</p>
<p>
 <a href="{%url 'votacao:listarquestao' %}"> Apagar questão</a>
</p>

<img src="{% static 'votacao/images/alvalade.jpg' %}">

sitepr/votacao/templates/votacao/joel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

sitepr/votacao/templates/votacao/listar_opcao.html
<h2>{{ questao.questao_texto }}</h2>
{% if error_message %}
 <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'votacao:apagaropcao' questao.id %}" method="post">
 {% csrf_token %}
 {% for opcao in questao.opcao_set.all %}
 <input type="radio" name="opcao" id="opcao" value="{{ opcao.id }}" />
 <label for="opcao">
 {{ opcao.opcao_texto }}
 </label>
 <br />
 {% endfor %}
 <input type="submit" value="Apagar opção e voltar à lista" />
</form>

sitepr/votacao/templates/votacao/listar_questao.html
<h3>Selecione uma questão para apagar</h3>
{% if error_message %}
 <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'votacao:apagarquestao' %}" method="post">
 {% csrf_token %}
 {% for questao in question_list %}
 <input type="radio" name="questao" id="questao{{ forloop.counter }}" value="{{ questao.id }}" />
 <label for="questao{{ forloop.counter }}">
 {{ questao.questao_texto }}
 </label>
 <br />
 {% endfor %}
 <input type="submit" value="Apagar questão e voltar à lista" />
</form>

sitepr/votacao/templates/votacao/nova_opcao.html
<h3>Questão: {{ questao.questao_texto }}</h3>
<form action="{% url 'votacao:gravaropcao' questao.id %}" method="post">
  {% csrf_token %}
  <label for="fnovaopcao">Nova opção:</label><br>
  <input type="text" id="fnovaopcao" name="fnovaopcao"><br>
  <input type="submit" value="Gravar opção e voltar à questão">
</form>

sitepr/votacao/templates/votacao/novaquestao.html
<h1>Nova Questão</h1>
<form action="{% url 'votacao:gravarquestao' %}" method="post">
  {% csrf_token %}
  <label for="fnovaquestao">Questão:</label><br>
  <input type="text" id="fnovaquestao" name="fnovaquestao"><br>
  <input type="submit" value="Gravar questão e voltar à lista">
</form>

sitepr/votacao/templates/votacao/resultados.html
<h1>{{ questao.questao_texto }}</h1>
<ul>
{% for opcao in questao.opcao_set.all %}
 <li>{{ opcao.opcao_texto }} --
 {{ opcao.votos }}
 voto{{ opcao.votos|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'votacao:detalhe' questao.id %}">Votar novamente?</a>