sitepr/projeto/urls.py
from django.urls import include, path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'projeto'
urlpatterns = [
 #index
 path("", views.index, name="index"),
 path("eventos" , views.eventos, name="eventos"),
 path("sobrenos" , views.sobrenos, name="sobrenos"),
 path("parceiros" , views.parceiros, name="parceiros"),
 path("user_login" , views.user_login, name="user_login"),
 path("registo" , views.registo, name="registo"),
 path("meus_eventos" , views.meus_eventos, name="meus_eventos"),
 path("meus_eventos/detalhe_meus_eventos/<int:evento_id>" , views.detalhe_meus_eventos, name="detalhe_meus_eventos"),
 path("meus_eventos/apagar_evento/<int:evento_id>", views.apagar_evento, name="apagar_evento"),
 path("eventos/criar_evento" , views.criar_evento, name="criar_evento"),
 path("registo/registar_org" , views.registar_org, name="registar_org"),
 path("eventos/<int:evento_id>" , views.detalhe_evento, name="detalhe_evento"),
 path("profile" , views.profile, name="profile"),
 path("logout" , views.logout_view, name="logout_view"),
 path('img_upload', views.img_upload, name='img_upload'),

]

if settings.DEBUG:
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitepr/sitepr/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
 path('votacao/', include('votacao.urls')),
 path('admin/', admin.site.urls),
 path('projeto/', include('projeto.urls')),
]

sitepr/projeto/models.py
from django.contrib.auth.models import User
from django.db import models
import datetime
# Create your models here.




class Organizacao(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, )
    nome = models.CharField(max_length=200)
    descricao = models.CharField(max_length=1000)
    img_name = models.CharField(max_length=1000, default='default_user.jpg')
    is_organizacao = models.BooleanField(default=True)
    def __str__(self):
       return self.nome


class Evento(models.Model):
    nome = models.CharField(max_length=200)
    descricao = models.CharField(max_length=1000)
    local = models.CharField(max_length=500)
    data = models.DateTimeField('data evento')
    organizacao = models.ForeignKey(Organizacao, on_delete=models.CASCADE)
    def __str__(self):
        return self.nome

sitepr/projeto/views.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db.models.functions import Lower
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from .models import Evento, Organizacao
from django.contrib.auth import authenticate, login, logout
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.utils import timezone
# Create your views here.

#PAGINA INICIAL
def index(request):
    return render(request, 'projeto/index.html')

def month_names(month):
    switcher = {
        1: "Janeiro",
        2: "Fevereiro",
        3: "Março",
        4: "Abril",
        5: "Maio",
        6: "Junho",
        7: "Julho",
        8: "Agosto",
        9: "Setembro",
        10: "Outubro",
        11: "Novembro",
        12: "Dezembro"
    }
    return switcher.get(month)


#PAGINA EVENTOS
def eventos(request):
    month = datetime.now().month
    current_month = month_names(month)
    next_month = month_names(month + 1)
    next_next_month = month_names(month + 2)
    current_month_list = Evento.objects.filter(data__month=month)
    next_month_list = Evento.objects.filter(data__month=month + 1)
    next_next_month_list = Evento.objects.filter(data__month=month + 2)
    context = {'current_month_list': current_month_list, 'next_month_list': next_month_list, 'next_next_month_list': next_next_month_list, 'current_month': current_month, 'next_month':next_month, 'next_next_month':next_next_month}
    return render(request, 'projeto/eventos.html',context)

#CRIAR EVENTO
def criar_evento(request):
    if request.method == "POST":
        u = request.user
        org = u.organizacao
        new_evento = Evento()
        new_evento.nome = request.POST['nome_evento']
        new_evento.descricao = request.POST['descricao_evento']
        new_evento.local = request.POST['local']
        new_evento.data = request.POST['data']
        new_evento.organizacao = org
        new_evento.save()
        return HttpResponseRedirect(reverse('projeto:eventos', ))
    else:
        return render(request, 'projeto/criar_evento.html')



#ABRIR OS DETALHES DE UM EVENTO
def detalhe_evento(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)
    return render(request, 'projeto/detalhe_evento.html', {'evento': evento})

#PAGINA MEUS EVENTOS
def meus_eventos(request):
    eventos_list = Evento.objects.filter(organizacao=request.user.organizacao).order_by('data')
    context = {'eventos_list': eventos_list}
    return render(request, 'projeto/meus_eventos.html',context)

def detalhe_meus_eventos(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)
    return render(request, 'projeto/apagar_evento.html',{'evento': evento})

def apagar_evento(request,evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)
    evento.delete()
    return HttpResponseRedirect(reverse('projeto:meus_eventos', ))

#PAGINA SOBRE NOS
def sobrenos(request):
    return render(request, 'projeto/sobre_nos.html')

#PAGINA PARCEIROS
def parceiros(request):
    org_list = Organizacao.objects.all()
    context = {'org_list': org_list}
    return render(request, 'projeto/parceiros.html', context)

#PAGINA LOGIN
def user_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # direccionar para página de sucesso
            return render(request, 'projeto/index.html')
        else:
            # direccionar para página de insucesso
            return render(request, 'projeto/login.html', {'error_message': "Utilizador não existe"})
    else:
        return render(request, 'projeto/login.html')


def logout_view(request):
    logout(request)
    return render(request, 'projeto/index.html')

#PAGINA REGISTAR
def registo(request):
    if request.method == "POST":
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        if username_exists(username):
            return render(request, 'projeto/registo.html', {'error_message': "Este utilizador já está registado"})
        elif email_exists(email):
            return render(request, 'projeto/registo.html', {'error_message': "Este utilizador já está registado"})
        elif password != confirm_password:
            return render(request, 'projeto/registo.html', {'error_message': "As passwords não coincidem"})
        else:
            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name
            user.save()
        return HttpResponseRedirect(reverse('projeto:user_login', ))
    else:
        return render(request, 'projeto/registo.html')

#validar se um username já existe
def username_exists(username):
    if User.objects.filter(username=username).exists():
        return True

    return False

#validar se um email já existe
def email_exists(email):
    if User.objects.filter(email=email).exists():
        return True

    return False




def registar_org(request):
    if request.method == 'POST' and request.FILES['img']:
        avatar = request.FILES['img']
        fs = FileSystemStorage()
        filename = fs.save(avatar.name, avatar)
        name_org = request.POST['name_org']
        bio = request.POST['bio']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        if username_exists(username):
            return render(request, 'projeto/registar_organizacao.html', {'error_message': "Este utilizador já está registado"})
        elif email_exists(email):
            return render(request, 'projeto/registar_organizacao.html', {'error_message': "Este utilizador já está registado"})
        elif password != confirm_password:
            return render(request, 'projeto/registar_organizacao.html', {'error_message': "As passwords não coincidem"})
        else:
            user = User.objects.create_user(username,email,password)
            org = Organizacao(user=user, nome=name_org, descricao=bio, img_name=avatar)
            org.save()
            user.save()
        return HttpResponseRedirect(reverse('projeto:user_login', ))
    else:
        return render(request, 'projeto/registar_organizacao.html')


def profile(request):
    return render(request, 'projeto/profile.html',)


def img_upload(request):
 if request.method == 'POST' and request.FILES['myfile']:
    myfile = request.FILES['myfile']
    fs = FileSystemStorage()
    filename = fs.save(myfile.name, myfile)
    uploaded_file_url = fs.url(filename)
    return render(request, 'projeto/img_upload.html', {'uploaded_file_url': uploaded_file_url})
 return render(request, 'projeto/img_upload.html')

sitepr/projeto/templates/projeto/apagar_evento.html
{% extends "projeto/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'projeto/eventos.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'projeto/detalhe_evento.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'projeto/titles.css' %}" />
{% endblock %}

{% block content %}



<div id="container">

    <!-- Start	Product details -->
        <div class="product-details">

            <!-- 	Nome Evento  -->
        <h1 class="heading">{{ evento.nome }}</h1>
        <span class="hint-star star">
            <i class="fa fa-star" aria-hidden="true"></i>
            <i class="fa fa-star" aria-hidden="true"></i>
            <i class="fa fa-star" aria-hidden="true"></i>
            <i class="fa fa-star-half-o" aria-hidden="true"></i>
            <i class="fa fa-star-o" aria-hidden="true"></i>
        </span>


    <!-- Info Evento  -->
            <p class="information">{{ evento.descricao }}</p>
            <p class="information">Organização: {{ evento.organizacao.nome }}</p>
            <p class="information">Local: {{ evento.local }}</p>
            <p class="information">Data: {{ evento.data }}</p>
            {% if user.is_authenticated and user.organizacao.is_organizacao %}



    <div class="control">
       <span class="shopping-cart"><i class="fa fa-shopping-cart" aria-hidden="true"></i></span>


    </div>

    </div>

    <!-- 	Imagem e Info -->

    <div class="product-image">
        {% with "/static/projeto/users/"|add:user.organizacao.img_name as imagem %}
        <img src="{{ imagem }}" alt="Imagem Organização">
        {% endwith %}
    <!-- 	Descrição -->
    <div class="info">
        <h3>Sobre nós</h3>
        <p>{{ user.organizacao.descricao }}</p>
        <br></br>
        <a href="{%url 'projeto:apagar_evento' evento.id %}" class="button5" style="background-color:red"> Apagar Evento </a>

    </div>
    </div>
    <!--  Fim Descrição  -->


    </div>

{% endif %}

{% endblock %}

sitepr/projeto/templates/projeto/criar_evento.html
{% extends "projeto/base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'projeto/login.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'projeto/titles.css' %}" />
{% endblock %}

{% block content %}
<title>Needins - Meus Eventos</title>

<br></br>
<br></br>
<form action="{% url 'projeto:criar_evento' %}" method="post">
  {% csrf_token %}
  <div class="box">
  <h1 class="heading">Criar Evento</h1>

  <input type="text" placeholder="Nome Evento" id="nome_evento" name="nome_evento" class="email" required/>
  <br></br>
  <input type="text" placeholder="Descrição" id="descricao_evento" name="descricao_evento" style="height: 60px; width:250px" class="email" required>
  <br></br>
  <input type="text" placeholder="Local" id="local" name="local" class="email" required>
  <br></br>
  <input type="datetime-local" id="data" name="data" class="email" required><br>

  {% if error_message %}
  <p style="color: red"><strong>{{ error_message }}</strong></p>
  {% endif %}

  <input type="submit" class="btn" value="Criar Evento">


  </div> <!-- End Box -->
</form>

{% endblock %}

sitepr/projeto/templates/projeto/detalhe_evento.html
{% extends "projeto/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'projeto/detalhe_evento.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'projeto/titles.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'projeto/button.css' %}" />
{% endblock %}

{% block content %}

<div id="container">

    <!-- Start	Product details -->
        <div class="product-details">

            <!-- 	Nome Evento  -->
        <h1>{{ evento.nome }}</h1>
        <span class="hint-star star">
            <i class="fa fa-star" aria-hidden="true"></i>
            <i class="fa fa-star" aria-hidden="true"></i>
            <i class="fa fa-star" aria-hidden="true"></i>
            <i class="fa fa-star-half-o" aria-hidden="true"></i>
            <i class="fa fa-star-o" aria-hidden="true"></i>
        </span>


    <!-- Info Evento  -->
            <p class="information">{{ evento.descricao }}</p>
            <p class="information">Organização: {{ evento.organizacao.nome }}</p>
            <p class="information">Local: {{ evento.local }}</p>
            <p class="information">Data: {{ evento.data }}</p>




    <div class="control">
       <span class="shopping-cart"><i class="fa fa-shopping-cart" aria-hidden="true"></i></span>


    </div>

    </div>
    <!-- 	Imagem e Info -->

    <div class="product-image">

        {% with "/static/projeto/users/"|add:evento.organizacao.img_name as imagem %}
        <img src="{{ imagem }}" alt="Imagem Organização">
        {% endwith %}
    <!-- 	Descrição -->
    <div class="info">
        <h2>Sobre nós</h2>
        <p>{{ evento.organizacao.descricao }}</p>
    </div>
    </div>
    <!--  Fim Descrição  -->


    </div>

{% endblock %}

sitepr/projeto/templates/projeto/eventos.html
{% extends "projeto/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'projeto/eventos.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'projeto/colunas.css' %}" />
{% endblock %}


{% block content %}
<title>Needins - Eventos</title>

<div class="row" style="background-color: #dfebe2">
    <div class="column" >
    <h2 style="text-align:center;text-shadow: 1px 1px 3px #6bba61;">{{ current_month }}</h2>

    {% if current_month_list %}
    {% for evento in current_month_list %}
        <div class="container">
            {% with "/static/projeto/users/"|add:evento.organizacao.img_name as imagem %}
            <img src="{{ imagem }}" alt="Avatar" width="90" height="90">
            {% endwith %}
            <p><span> {{ evento.nome }} - {{ evento.organizacao.nome }} </span></p>
            <p> {{ evento.data }} </p>
            <a href="{%url 'projeto:detalhe_evento' evento.id %}" class="btn"> Informações </a>
        </div>
    {% endfor %}

    {% else %}
    <p style="text-align:center">Não há Eventos disponiveis.</p>
    {% endif %}
    </div>

    <div class="column">
    <h2 style="text-align:center;text-shadow: 1px 1px 3px #6bba61;">{{ next_month }}</h2>
    {% if next_month_list %}
    {% for evento in next_month_list %}
        <div class="container">
            {% with "/static/projeto/users/"|add:evento.organizacao.img_name as imagem %}
            <img src="{{ imagem }}" alt="Avatar" width="90" height="90">
            {% endwith %}
            <p><span> {{ evento.nome }} - {{ evento.organizacao.nome }} </span></p>
            <p> {{ evento.data }} </p>
            <a href="{%url 'projeto:detalhe_evento' evento.id %}" class="btn"> Informações </a>
        </div>
    {% endfor %}

    {% else %}
    <p style="text-align:center">Não há Eventos disponiveis.</p>
    {% endif %}
    </div>

    <div class="column">
    <h2 style="text-align:center;text-shadow: 1px 1px 3px #6bba61;">{{ next_next_month }}</h2>
    {% if next_next_month_list %}
    {% for evento in next_next_month_list %}
        <div class="container">
            {% with "/static/projeto/users/"|add:evento.organizacao.img_name as imagem %}
            <img src="{{ imagem }}" alt="Avatar" width="90" height="90">
            {% endwith %}
            <p><span> {{ evento.nome }} - {{ evento.organizacao.nome }} </span></p>
            <p> {{ evento.data }} </p>
            <a href="{%url 'projeto:detalhe_evento' evento.id %}" class="btn"> Informações </a>
        </div>
    {% endfor %}

    {% else %}
    <p style="text-align:center">Não há Eventos disponiveis.</p>
    {% endif %}
    </div>

</div>



{% endblock %}

sitepr/projeto/templates/projeto/img_upload.html
{% load static %}
 <form method="post" enctype="multipart/form-data" action="{% url 'projeto:img_upload' %}">
 {% csrf_token %}
 <input type="file" name="myfile">
 <input type="submit" value="Upload">
 </form>

 {% if uploaded_file_url %}
 <p>Feito o upload para: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
 {% endif %}
 <p><a href="{% url 'projeto:index' %}">Voltar ao inicio</a></p>

sitepr/projeto/templates/projeto/index.html
{% extends "projeto/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'projeto/index.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'projeto/titles.css' %}" />
{% endblock %}


{% block content %}
<title>Needins - Homepage</title>


<img src="{% static 'projeto/images/needinslogo2.png' %}" alt="Imagem Central" class="center">


    <div id="features">
        <div class="wrapper">
            <ul>
                <li class="feature-1">
                    <h4>SOLUÇÕES DIGITAIS</h4>
                    <p>Usa a tecnologia como solução à necessidade</p>
                </li>
                <li class="feature-2">
                    <h4>LOCALIZA ORGANIZAÇÕES</h4>
                    <p>Encontra as organizações que procuras</p>
                </li>
                <li class="feature-3">
                    <h4>ENTREGA DE BENS</h4>
                    <p>Entrega alimentos e outros bens às nossas organizações parceiras</p>
                </li>
                <div class="clear">
                </div>
            </ul>
        </div>
    </div>


<br></br>



    <div id="cta">
        <div class="wrapper">
            <h3>QUERES SABER MAIS?</h3>
            <p>A NEEDINS é uma plataforma que visa facilitar a entrega de bens essenciais nestes dias tão difíceis que vivemos. Com o decorrer da pandemia, a entrega de alimentos e outros bens não tem estado tão presente nas nossas vidas. </p>
            <a href="{% url 'projeto:sobrenos' %}" class="button-2">Sobre nós</a>
        </div>
    </div>




<br></br>



{% endblock %}

sitepr/projeto/templates/projeto/index_teste.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'projeto/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'projeto/index.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'projeto/header_2.css' %}" />

<title>
    Needins - Homepage
</title>
<body>
    <header>

    <nav>
        <ul class="nav__links">
        <li><a href="{% url 'projeto:index' %}">INÍCIO</a></li>
        <li><a href="{% url 'projeto:eventos' %}">EVENTOS</a></li>
        <li><a href="{% url 'projeto:parceiros' %}">PARCEIROS</a></li>
        <li><a href="{% url 'projeto:sobrenos' %}">SOBRE NÓS</a></li>
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'projeto:profile' %}">PROFILE</a></li>
        {% else %}
        <li><a href="{% url 'projeto:user_login' %}">LOGIN</a></li>
        <li><a href="{% url 'projeto:registo' %}">REGISTAR</a></li>
        {% endif %}
        </ul>
    </nav>
    </header>
</body>

<div class="footer">
    <p>NEEDINS | Copyright 2021</p>
</div>

<!--<img src="{% static 'projeto/images/logoneedins.png' %}" alt="Paris"  width="40"  height="25" class="header a.logo"> -->
<img src="{% static 'projeto/images/logo needins.png' %}" alt="Imagem Central" class="center">
<img src="{% static 'projeto/images/principal.jpeg' %}" alt="Imagem Central" class="center">

<a href="{% url 'projeto:img_upload' %}">upload</a>

sitepr/projeto/templates/projeto/login.html
{% extends "projeto/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'projeto/login.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'projeto/titles.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'projeto/button.css' %}" />
{% endblock %}

{% block content %}
<br></br>
<br></br>
<title>Needins - Login</title>

<form action="{% url 'projeto:user_login' %}" method="post">
    {% csrf_token %}
    <div class="box">
    <h1 class="heading">Login</h1>

    <input type="text" placeholder="Username" id="username" name="username" required oninvalid="this.setCustomValidity('Este campo é obrigatório.')" oninput="this.setCustomValidity('')" class="email" />
    <br></br>
    <input type="password" placeholder="Palavra-passe" id="password" name="password" required oninvalid="this.setCustomValidity('Este campo é obrigatório.')" oninput="this.setCustomValidity('')" class="email" />
    <br></br>
    {% if error_message %}
    <p style="color: red"><strong>{{ error_message }}</strong></p>
    {% endif %}

    <input type="submit" class="btn" value="Continuar">


    </div> <!-- End Box -->
</form>



{% endblock %}

sitepr/projeto/templates/projeto/meus_eventos.html
{% extends "projeto/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'projeto/eventos.css' %}" />
{% endblock %}

{% block content %}
<title>Needins - Meus Eventos</title>

<h1 style="text-align:center;text-shadow: 1px 1px 3px #6bba61;">Meus eventos</h1>
<br></br>
<div style="background-color:#dfebe2;padding: 40px">
{% if eventos_list %}
    {% for evento in eventos_list %}
        <div class="container" style="display: block;margin-left: auto;margin-right: auto;margin-top: 10px;width: 60%;">
            {% with "/static/projeto/users/"|add:evento.organizacao.img_name as imagem %}
            <img src="{{ imagem }}" alt="Avatar" width="90" height="90">
            {% endwith %}
            <p><span> {{ evento.nome }} - {{ evento.organizacao.nome }} </span></p>
            <p> {{ evento.data }} </p>
            <a href="{%url 'projeto:detalhe_meus_eventos' evento.id %}" class="btn"> Detalhes </a>
        </div>
    {% endfor %}
{% else %}
<p>Não tens eventos criados.</p>
{% endif %}


{% if user.is_authenticated and user.organizacao.is_organizacao %}
<p>
 <a href="{%url 'projeto:criar_evento' %}" class="button5" style="margin-left:20%"> Criar Evento </a>
</p>
{% endif %}
</div>

{% endblock %}

sitepr/projeto/templates/projeto/profile.html
{% extends "projeto/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'projeto/profile.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'projeto/titles.css' %}" />
{% endblock %}

{% block content %}

<title>Needins - Profile</title>
<br></br>
<h2 style="text-align:center" class="heading">Profile</h2>



{% if request.user.is_authenticated and not user.organizacao.is_organizacao %}
<div class="card">
  <img src="{% static 'projeto/images/user.png' %}" alt="Utilizador" style="width:100%">
  <h1>{{user.get_username}}</h1>
  <p class="title">{{ user.first_name }} {{ user.last_name }}</p>
  <p>{{ user.email }}</p>
  <a href="{% url 'projeto:logout_view' %}" class="button5" style="background-color:red">LOGOUT</a>
</div>
{% endif %}


{% if user.is_authenticated and user.organizacao.is_organizacao %}
<div class="card">
    {% with "/static/projeto/users/"|add:user.organizacao.img_name as imagem %}
    <img src="{{ imagem }}" alt="Imagem" style="width:100%">
    {% endwith %}
    <h1>{{user.get_username}}</h1>
    <p class="title">{{ user.organizacao.nome }}</p>
    <p>{{ user.organizacao.descricao }}</p>
    <p>{{ user.email }}</p>
    <a href="{% url 'projeto:logout_view' %}" class="button5" style="background-color:red">LOGOUT</a>
</div>
{% endif %}


{% endblock %}

sitepr/projeto/templates/projeto/registo.html
{% extends "projeto/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'projeto/login.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'projeto/titles.css' %}" />
{% endblock %}


{% block content %}
<title>Needins - Registo</title>
<br></br>
<br></br>
<form action="{% url 'projeto:registo' %}" method="post">

    {% csrf_token %}
    <div class="box">
    <h1 class="heading">Registo</h1>

    <input type="text" placeholder="Nome" id="first_name" name="first_name" class="email" >
    <br></br>
    <input type="text" placeholder="Apelido" id="last_name" name="last_name" class="email">
    <br></br>
    <input type="text" placeholder="Username" id="username"  name="username" required oninvalid="this.setCustomValidity('Este campo é obrigatório.')" oninput="this.setCustomValidity('')"  class="email"/>
    <br></br>
    <input type="email" placeholder="e-mail@gmail.com" id="email" name="email" required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" oninvalid="this.setCustomValidity('Este campo é obrigatório. Preencha como no exemplo.')" oninput="this.setCustomValidity('')" class="email" >
    <br></br>
    <input type="password" placeholder="Insere a Palavra-passe" id="password" name="password" required oninvalid="this.setCustomValidity('Este campo é obrigatório')" oninput="this.setCustomValidity('')" class="email" >
    <br></br>
    <input type="password" placeholder="Confirma a Palavra-passe" id="confirm_password" name="confirm_password" required oninvalid="this.setCustomValidity('Este campo é obrigatório')" oninput="this.setCustomValidity('')" class="email" >
    <br></br>
    {% if error_message %}
    <p style="color: red"><strong>{{ error_message }}</strong></p>
    {% endif %}

    <input type="submit" class="btn" value="Continuar">


    </div> <!-- End Box -->
</form>

<a class="button5" href="{% url 'projeto:registar_org' %}">Registar como Organização</a>

{% endblock %}

sitepr/projeto/templates/projeto/user_login.html
  
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'projeto/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'projeto/index.css' %}" />

<div class="header">
    <a href="{% url 'projeto:index' %}" class="logo">NEEDINS</a>
    <div class="header-right">
        <a class="active" href="{% url 'projeto:index' %}">INÍCIO</a>
        <a href="{% url 'projeto:eventos' %}">EVENTOS</a>
        <a href="{% url 'projeto:parceiros' %}">PARCEIROS</a>
        <a href="{% url 'projeto:sobrenos' %}">SOBRE NÓS</a>
        <a>PROFILE</a>

    </div>
</div>

<div class="footer">
    <p>NEEDINS | Copyright 2021</p>
</div>

<!--<img src="{% static 'projeto/images/logoneedins.png' %}" alt="Paris"  width="40"  height="25" class="header a.logo"> -->
<img src="{% static 'projeto/images/needins2.png' %}" alt="Imagem Central" class="center">